"""add FL, equipment combo, notifications, work orders

Revision ID: 28e1f967faf1
Revises: 71eeb6ac4f01
Create Date: 2025-05-07 16:25:05.817734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e1f967faf1'
down_revision = '71eeb6ac4f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functional_location',
    sa.Column('fl_id', sa.String(length=20), nullable=False),
    sa.Column('fl_name', sa.String(length=100), nullable=True),
    sa.Column('plant_id', sa.String(length=10), nullable=True),
    sa.Column('parent_fl_id', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_fl_id'], ['functional_location.fl_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['maintenance_plant.plant_id'], ),
    sa.PrimaryKeyConstraint('fl_id')
    )
    op.create_table('fl_equipment_combination',
    sa.Column('combination_id', sa.Integer(), nullable=False),
    sa.Column('fl_id', sa.String(length=20), nullable=True),
    sa.Column('equipment_id', sa.String(length=20), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('removal_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['fl_id'], ['functional_location.fl_id'], ),
    sa.PrimaryKeyConstraint('combination_id')
    )
    op.create_table('maintenance_notification',
    sa.Column('notification_id', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('fl_id', sa.String(length=20), nullable=True),
    sa.Column('equipment_id', sa.String(length=20), nullable=True),
    sa.Column('planned_unplanned', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['fl_id'], ['functional_location.fl_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('maintenance_work_order',
    sa.Column('work_order_id', sa.String(length=20), nullable=False),
    sa.Column('notification_id', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('planning_plant_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['maintenance_notification.notification_id'], ),
    sa.ForeignKeyConstraint(['planning_plant_id'], ['planning_plant.planning_plant_id'], ),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_work_order')
    op.drop_table('maintenance_notification')
    op.drop_table('fl_equipment_combination')
    op.drop_table('functional_location')
    # ### end Alembic commands ###
