"""initial schema

Revision ID: 71eeb6ac4f01
Revises: bb37198148ba
Create Date: 2025-05-07 16:02:44.558931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71eeb6ac4f01'
down_revision = 'bb37198148ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_plant',
    sa.Column('plant_id', sa.String(length=10), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('planning_plant',
    sa.Column('planning_plant_id', sa.String(length=10), nullable=False),
    sa.Column('planning_name', sa.String(length=100), nullable=True),
    sa.Column('associated_plant_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['associated_plant_id'], ['maintenance_plant.plant_id'], ),
    sa.PrimaryKeyConstraint('planning_plant_id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_plant_id', sa.String(length=10), nullable=False))
        batch_op.create_foreign_key(None, 'planning_plant', ['planning_plant_id'], ['planning_plant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planning_plant_id')

    op.drop_table('planning_plant')
    op.drop_table('maintenance_plant')
    # ### end Alembic commands ###
