"""initial schema

Revision ID: bb37198148ba
Revises: 
Create Date: 2025-05-07 15:50:48.715822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb37198148ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    # ### end Alembic commands ###
